# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-15 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0007_auto_20190415_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='refresh',
            field=models.IntegerField(default=3000, help_text='\u6570\u636e\u5237\u65b0\u65f6\u95f4', verbose_name="Data's refresh"),
        ),
    ]
