# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-16 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0013_auto_20190415_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='trend',
            name='air',
            field=models.IntegerField(default=0, help_text='\u5929\u7a97\u5f00\u5ea6\u5386\u53f2\u6570\u636e', verbose_name="Air's trend"),
        ),
    ]
