# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-17 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0014_trend_air'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skylight_position_manual', models.BooleanField(default=False, help_text='\u901a\u98ce\u8bbe\u5907\u624b\u52a8switch', verbose_name='Skylight manual control')),
            ],
        ),
    ]
