# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-18 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0020_auto_20190418_0454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sunshade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check', models.BooleanField(default=0, help_text='\u8ba1\u5212\u542f\u7528\u9009\u62e9', verbose_name='sunshade plan checkbox')),
                ('time', models.CharField(help_text='\u5929\u7a97\u52a8\u4f5c\u65f6\u95f4', max_length=32, verbose_name='sunshade time node')),
                ('position', models.IntegerField(help_text='\u5929\u7a97\u52a8\u4f5c\u4f4d\u7f6e', verbose_name='sunshade position node')),
            ],
        ),
        migrations.AddField(
            model_name='apps',
            name='sunshade_position_manual',
            field=models.BooleanField(default=0, help_text='\u906e\u9633\u8bbe\u5907\u624b\u52a8switch', verbose_name='Sunshade manual control'),
        ),
    ]
