# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-11 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0004_themes_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='smartCity', help_text='\u5e94\u7528\u6807\u9898', max_length=32, verbose_name="Project's name")),
                ('position', models.CharField(default='local', max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='themes',
            name='position',
        ),
        migrations.RemoveField(
            model_name='themes',
            name='title',
        ),
    ]
