# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-15 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0006_auto_20190412_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='refresh',
            field=models.CharField(default=3000, help_text='\u6570\u636e\u5237\u65b0\u65f6\u95f4', max_length=32, verbose_name="Data's refresh"),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default='\u73af\u5883\u76d1\u63a7', help_text='\u5e94\u7528\u540d\u79f0', max_length=32, verbose_name="App's name"),
        ),
        migrations.AlterField(
            model_name='project',
            name='position',
            field=models.CharField(default='\u9633\u5149\u623f', help_text='\u5e94\u7528\u4f4d\u7f6e', max_length=32, verbose_name="App's position"),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(default='\u667a\u6167\u57ce\u5e02', help_text='\u5e94\u7528\u6807\u9898', max_length=32, verbose_name="Project's name"),
        ),
    ]
