# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-15 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0011_auto_20190415_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trend',
            name='time',
            field=models.TimeField(help_text='\u5386\u53f2\u65f6\u95f4', verbose_name='Time'),
        ),
    ]
