# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-17 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0015_apps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apps',
            name='skylight_position_manual',
            field=models.BooleanField(help_text='\u901a\u98ce\u8bbe\u5907\u624b\u52a8switch', verbose_name='Skylight manual control'),
        ),
    ]
