# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-17 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0017_auto_20190417_0320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skylight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(help_text='\u5929\u7a97\u52a8\u4f5c\u65f6\u95f4', verbose_name='Skylight time node')),
                ('position', models.IntegerField(help_text='\u5929\u7a97\u52a8\u4f5c\u4f4d\u7f6e', verbose_name='Skylight position node')),
            ],
        ),
    ]
