# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-15 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0012_auto_20190415_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trend',
            name='gas',
            field=models.FloatField(help_text='\u6709\u5bb3\u6c14\u4f53\u5386\u53f2\u6570\u636e', verbose_name='Gas trend'),
        ),
        migrations.AlterField(
            model_name='trend',
            name='humidity',
            field=models.FloatField(help_text='\u6e7f\u5ea6\u5386\u53f2\u6570\u636e', verbose_name="Humidity's trend"),
        ),
        migrations.AlterField(
            model_name='trend',
            name='light',
            field=models.FloatField(help_text='\u5149\u7167\u5386\u53f2\u6570\u636e', verbose_name="Light's trend"),
        ),
        migrations.AlterField(
            model_name='trend',
            name='noise',
            field=models.FloatField(help_text='\u566a\u58f0\u5386\u53f2\u6570\u636e', verbose_name="Noise's trend"),
        ),
        migrations.AlterField(
            model_name='trend',
            name='temperature',
            field=models.FloatField(help_text='\u6e29\u5ea6\u5386\u53f2\u6570\u636e', verbose_name="Temperature's trend"),
        ),
        migrations.AlterField(
            model_name='trend',
            name='time',
            field=models.DateTimeField(help_text='\u5386\u53f2\u65f6\u95f4', verbose_name='Time'),
        ),
    ]
