# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-18 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0018_skylight'),
    ]

    operations = [
        migrations.AddField(
            model_name='skylight',
            name='check',
            field=models.BooleanField(default=0, help_text='\u8ba1\u5212\u542f\u7528\u9009\u62e9', verbose_name='Skylight plan checkbox'),
        ),
    ]
