# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-18 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0019_skylight_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skylight',
            name='time',
            field=models.CharField(help_text='\u5929\u7a97\u52a8\u4f5c\u65f6\u95f4', max_length=32, verbose_name='Skylight time node'),
        ),
    ]
