# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-18 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0021_auto_20190418_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sunshade',
            name='position',
            field=models.IntegerField(help_text='\u906e\u9633\u52a8\u4f5c\u4f4d\u7f6e', verbose_name='sunshade position node'),
        ),
        migrations.AlterField(
            model_name='sunshade',
            name='time',
            field=models.CharField(help_text='\u906e\u9633\u52a8\u4f5c\u65f6\u95f4', max_length=32, verbose_name='sunshade time node'),
        ),
    ]
